name: mobile_application
description: A new Flutter project.
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  hexcolor: ^3.0.1
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.10.0
  firebase_core: ^2.16.0
  introduction_screen: ^2.1.0
  shared_preferences: ^2.0.11
  flutter_image_slideshow: ^0.1.6
  image_picker: ^1.0.4
  flutter_launcher_icons: ^0.13.1
  

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "Assets/icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0



flutter:
  uses-material-design: true
  
  assets:
    - assets/
    - assets/welcome.png
    - assets/Skillup.png
    - assets/Mask44.png
    - assets/Maskgroup.png
    - assets/Mask33.png
    - assets/signup.png
    - assets/Msignin.png
    - assets/slideshow1.png
    - assets/second.png
    - assets/path1.png
    - assets/third.png
    - assets/verify2.png
    - assets/java1.png
    - assets/aiImage.png
    - assets/profile_photo.jpg
    - assets/image1.jpg
    - assets/image2.png
